name: fletch
version: 0.2.0
author: Rob Kellett <rob@kelle.tt>
description: A jQuery-like library implemented using common Dart patterns.
homepage: https://github.com/RobKellett/Fletch
documentation: https://robkellett.github.io/Fletch/
dependencies:
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  unittest: any
